- GNUmakefile
- commands/fetchredhat.go
- commands/selectredhat.go
- db/db.go
- lock.json
- main.go
- manifest.json
- models/models.go
- models/redhat.go
- redhat/redhat.go
$ go build  && ./goval-dictionary fetch-redhat  7
$ go build && ./goval-dictionary select-redhat RedHat 7 golang
```
CVE-2015-5739
{3399 319 golang 0:1.6.3-1.el7_2.1}
{3400 319 golang-bin 0:1.6.3-1.el7_2.1}
{3401 319 golang-docs 0:1.6.3-1.el7_2.1}
{3402 319 golang-misc 0:1.6.3-1.el7_2.1}
{3403 319 golang-src 0:1.6.3-1.el7_2.1}
{3404 319 golang-tests 0:1.6.3-1.el7_2.1}
CVE-2015-5740
{3399 319 golang 0:1.6.3-1.el7_2.1}
{3400 319 golang-bin 0:1.6.3-1.el7_2.1}
{3401 319 golang-docs 0:1.6.3-1.el7_2.1}
{3402 319 golang-misc 0:1.6.3-1.el7_2.1}
{3403 319 golang-src 0:1.6.3-1.el7_2.1}
{3404 319 golang-tests 0:1.6.3-1.el7_2.1}
CVE-2015-5741
{3399 319 golang 0:1.6.3-1.el7_2.1}
{3400 319 golang-bin 0:1.6.3-1.el7_2.1}
{3401 319 golang-docs 0:1.6.3-1.el7_2.1}
{3402 319 golang-misc 0:1.6.3-1.el7_2.1} …
```
> DB insert/select

- config/config.go
- server/server.go
I change ovaldb keyname to lowercase.
> change ovaldb keyname to lowercase

- Gopkg.lock
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- commands/server.go
- db/db.go
- db/rdb/rdb.go
- db/redis.go
- fetcher/ubuntu.go
1. add CloseDB
2. put OpenDB and MigrateDB into NewDB.
3. fix log library(it is my fault)
> improve new method of databse

- db/redis.go
fix  osVe to use it  as a major os version.
> fix os version @redis driver

- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- commands/server.go
- fix typo (cve.sqlite3 -> oval.sqlite3)
- fix spacing
> fix command usage text

- Gopkg.lock
- Gopkg.toml
- README.md
- commands/fetch-alpine.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/select.go
- config/config.go
- db/rdb/alpine.go
- db/rdb/rdb.go
- db/rdb/redhat.go
- db/rdb/ubuntu.go
- db/redis.go
- fetcher/alpine.go
- fetcher/redhat.go
- fetcher/util.go
- main.go
- models/alpine.go
#21 
https://github.com/future-architect/vuls/issues/194
> Alpine Support, Bugfix of refreshing RDB

- README.md
- commands/fetch-amazon.go
- commands/select.go
- config/config.go
- db/rdb/alpine.go
- db/rdb/amazon.go
- db/rdb/debian.go
- db/rdb/oracle.go
- db/rdb/rdb.go
- db/rdb/redhat.go
- db/rdb/suse.go
- db/redis.go
- fetcher/amazon.go
- main.go
- models/alpine.go
- models/amazon.go
https://alas.aws.amazon.com/alas.rss
> Support Amazon Linux RSS 

- README.md
- commands/fetch-ubuntu.go
- config/config.go
- fetcher/ubuntu.go
Link: https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml
> feat(fetcher): support Ubuntu18 OVAL

- db/rdb/debian.go
- db/rdb/oracle.go
- db/rdb/rdb.go
- db/rdb/redhat.go
- db/rdb/suse.go
- db/rdb/ubuntu.go
> fix(fetch): tx.Rollback before return from a function to avoid nil pointer #39

- fetcher/util.go
Finish takes only gerund and wh- clauses as complements:
e.g finished read'ing' , or finish 'wh'at i was doing 
https://ell.stackexchange.com/questions/40022/is-just-finished-to-right
;)
> fixing grammar

- fetcher/alpine.go
- fetcher/amazon.go
- fetcher/debian.go
- fetcher/oracle.go
- fetcher/redhat.go
- fetcher/suse.go
- fetcher/ubuntu.go
- fetcher/util.go
https://github.com/future-architect/vuls/issues/698
> fix(fetch): fix 403 while fetching redhat oval

- models/models.go
closes #45 
https://github.com/jinzhu/gorm/issues/510#issuecomment-180669092
> fix(fetch-ubuntu): fix fetch error `more_info is too long`

- db/redis.go
When using Redis, it also returns packages of different major versions in the case of RedHat.
> fix(redhat): add filterByRedHatMajor

- models/ubuntu.go
- models/ubuntu_test.go
> fix(ubuntu): trim suffix `The` of pkgname in Ubuntu14 OVAL

- GNUmakefile
- models/ubuntu.go
- models/ubuntu_test.go
see 
https://github.com/kotakanbe/goval-dictionary/issues/61
> fix(fetch-ubuntu14): trim last space from version

- commands/fetch-alpine.go
- commands/fetch-amazon.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- db/db.go
- db/rdb/rdb.go
- db/redis.go
- server/server.go
Changed GetByPkgName function to receive family.
Relatedly fix vuls.
> Change GetByPkgName interface 

- config/config.go
- fetcher/ubuntu.go
Fetch Ubuntu 17 (artful) oval data
> Fetch Ubuntu 17 Oval data

- db/rdb/alpine.go
- db/rdb/debian.go
- db/rdb/ubuntu.go
https://github.com/future-architect/vuls/issues/886
> fix(db): too many sql variables

- commands/fetch-alpine.go
- commands/fetch-amazon.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- commands/server.go
- db/rdb/rdb.go
- db/rdb/redhat.go
- fetcher/amazon.go
- models/models.go
- models/redhat.go
- models/redhat_test.go
- util/util.go
```
...
<criterion comment="Red Hat Enterprise Linux 8 is installed" test_ref="oval:com.redhat.rhba:tst:20193384074"/>
<criterion comment="Module postgresql:9.6 is enabled" test_ref="oval:com.redhat.rhsa:tst:20205619025"/>
...
```
```
sqlite> select defs.definition_id, pkgs.modularity_label, pkgs.name, pkgs.version from packages pkgs, definitions defs where defs.id = pkgs.definition_id and  modularity_label != "" ;
```
```
sqlite> .schema packages
CREATE TABLE IF NOT EXISTS "packages" ("id" integer primary key autoincrement,"definition_id" integer,"name" varchar(255),"version" varchar(255),"arch" varchar(255),"not_fixed_yet" bool,"modularity_label" varchar(255) );
CREATE INDEX idx_packages_definition_id ON "packages"(definition_id) ;
CREATE …
```
> support dnf modules in RHEL8 OVAL

- db/redis.go
I removed log output of `Opening DB.`
> remove log of opening db

- db/redis.go
> fix(oracle): collect arch info in OVAL for redis-backend

- commands/fetch-alpine.go
- commands/fetch-amazon.go
- db/db.go
- db/rdb/alpine.go
- db/rdb/amazon.go
- db/rdb/debian.go
- db/rdb/oracle.go
- db/rdb/rdb.go
- db/rdb/redhat.go
- db/rdb/suse.go
- db/rdb/ubuntu.go
- db/redis.go
- server/server.go
```console
$ goval-dictionary fetch-redhat 8
$ goval-dictionary fetch-debian 10
$ goval-dictionary fetch-ubuntu 20
// commit: 1eb8c5e8eca4a032a4e6d47946ab6f2263ef406e
$ goval-dictionary server
$ curl http://127.0.0.1:1324/count/redhat/8
0
$ curl http://127.0.0.1:1324/count/debian/10
0
$ curl http://127.0.0.1:1324/count/ubuntu/20
0 
// PR
$ goval-dictionary server
$ curl http://127.0.0.1:1324/count/redhat/8
598
$ curl http://127.0.0.1:1324/count/debian/10
17912
$ curl http://127.0.0.1:1324/count/ubuntu/20
8001
$ goval-dictionary fetch-alpine 3.3 3.4 3.5 3.6
$ goval-dictionary fetch-amazon
$ sqlite3 oval.sqlite3
sqlite> select * from fetch_meta;
id|file_name|timestamp
1|secdb.alpinelinux.org/v3.4|2021-06-25 13:10:01.793666062+09:00
2|secdb.alpinelinux.org/v3.6|2021-06-25 …
```
> fix: error handling

- README.md
- config/config.go
- fetcher/ubuntu.go
Support
Fixes #127 
```
[vuls@vuls ~]$ goval-dictionary fetch-ubuntu 18 20 21
INFO[04-28|13:07:13] Fetching...                              URL=https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.bionic.cve.oval.xml.bz2
INFO[04-28|13:07:13] Fetching...                              URL=https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.focal.cve.oval.xml.bz2
INFO[04-28|13:07:13] Fetching...                              URL=https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.hirsute.cve.oval.xml.bz2
INFO[04-28|13:07:17] Fetched...                               URL=https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.hirsute.cve.o …
```
> feat: Support Ubuntu21 (#127)

- commands/fetch-alpine.go
- commands/fetch-amazon.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- commands/server.go
- db/db.go
- db/rdb.go
- db/redis.go
refactor: remove redundant logging
make build
> refactor: remove redundant logging

- db/redis.go
https://github.com/vulsio/goval-dictionary/pull/164
> chore: add a continue statement

- commands/fetch-amazon.go
- db/db.go
- fetcher/amazon.go
fetch amazon linux 2022 CVEs
https://github.com/vulsio/goval-dictionary/pull/169#pullrequestreview-815545601
> fetch amazon linux 2022 CVEs

- db/rdb.go
OS other than Amazon/Oracle do not have Arch information in Package. With the current query, when searching for vuls with arch information, there is a problem that OS such as Debian cannot be scanned correctly.
This bug was not noticed because the integration test uses server mode, so it is not searched in Debian with arch information.
Using CentOS8, here are the differences in the search results for vuls.
When using master mod, the number of OVAL detections is 0, while when using MaineK00n/fix-rdb-query, the number of OVAL detections is 171.
```console
$ vuls report -format-one-line-text
[Dec  9 02:33:18]  INFO [localhost] vuls-v0.19.0-build-20211207_094022_0c6a892
[Dec  9 02:33:18]  INFO [localhost] Validating config...
[Dec  9 02:33:18]  INFO [localhost] cveDict.type=sqlite3, …
```
> fix(rdb): change query to Package Arch for each OS

- models/suse/suse.go
- models/suse/suse_test.go
Fixed walk in OVAL.
Compare the number of fetches with the master.
|   fetch openSUSE version  | 10.2 | 10.3 | 11.0 | 11.1 | 11.2 | 11.3 | 11.4 | 12.1 | 12.2 | 12.3 | 13.1 | 13.2 | tumbleweed |
|:-------------------------:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|:----------:|
|          master(031fc96)         |  905 | 1095 | 1184 | 1196 | 1161 | 1231 |  644 | 1267 | 1013 | 1256 | 2852 | 5145 |    11867   |
| MaineK00n/fix-suse-walk |  905 | 1095 | 1184 | 1196 | 1161 | 1231 |  644 | 1267 | 1013 | 1256 | 2852 | 5145 |    11867   |
| fetch openSUSE Leap version | 42.1 | 42.2 | 42.3 | 15.0 | 15.1 | 15.2 | 15.3 |
|:---------------------------:|:----:|:----:|:----:|:----:|:----:|:----:|:----:|
|           master(031fc96)          | 4760 | 5662 | 7189 …
> fix(suse): fix oval walk

- commands/fetch-alpine.go
Fixes #211 
alpine secdb has two files, main.yaml and community.yaml, and inserts each of them. Therefore, one of the inserts failed.
Integrate main.yaml and community.yaml before inserting.
```console
$ goval-dictionary fetch alpine 3.15
INFO[03-07|06:34:57] Fetching...                              URL=https://secdb.alpinelinux.org/v3.15/main.yaml
INFO[03-07|06:34:57] Fetching...                              URL=https://secdb.alpinelinux.org/v3.15/community.yaml
INFO[03-07|06:34:59] Refreshing...                            Family=alpine Version=3.15
INFO[03-07|06:34:59] Inserting new Definitions... 
1581 / 1581 [-------------------------------------------------------------------] 100.00% ? p/s
INFO[03-07|06:34:59] Finish                                   Updated=1581
INFO[03-07|06:34:59] …
```
> fix(alpine): fix OVAL insert

- .github/workflows/docker-build.yml
- .github/workflows/golangci.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
- .goreleaser.yml
- go.mod
- go.sum
- main.go
When an error occurs, use stderr instead of stdout.
```console
$ goval-dictionary fetch ubuntu 22 --dbtype redis --dbpath "redis://127.0.0.1:6379" 1>/dev/null
Failed to open DB. err: Failed to open DB. dbtype: redis, dbpath: redis://127.0.0.1:6379, err: dial tcp 127.0.0.1:6379: connect: connection refused
```
> chore: print to stderr

- models/models.go
#274 has two parts: changing the GORM type and adding periodic integration tests to guarantee the entire fetch. I split the PR to discuss the latter more.
fixes #273
```console
$ goval-dictionary version
goval-dictionary v0.8.1 7ad1e88
$ goval-dictionary fetch ubuntu 22 --dbtype postgres --dbpath "host=localhost user=postgres dbname=postgres sslmode=disable password=postgres"
INFO[02-09|20:40:05] Fetching...                              URL=https://security-metadata.canonical.com/oval/com.ubuntu.jammy.cve.oval.xml.bz2
INFO[02-09|20:40:10] Fetched                                  File=com.ubuntu.jammy.cve.oval.xml.bz2 Count=11081 Timestamp=2023-02-09T07:56:50
INFO[02-09|20:40:10] Refreshing...                            Family=ubuntu Version=22
INFO[02-09|20:40:10] Inserting new …
```
> fix(fetch): change GORM type due to overflow

- commands/fetch-amazon.go
- db/db.go
- db/db_test.go
- fetcher/amazon/amazon.go
- fetch Amazon Linux 2023 CVEs
- Change Amazon Linux 2022 releasemd.xml url(al2022ReleasemdURI)
```
INFO[03-16|12:59:40] Fetching...                              URL=https://cdn.amazonlinux.com/al2022/core/releasemd.xml
INFO[03-16|12:59:41] Fetching...                              URL=https://cdn.amazonlinux.com/al2022/core/mirrors/2022.0.20230118/x86_64/mirror.list
INFO[03-16|12:59:41] Fetching...                              URL=https://cdn.amazonlinux.com/al2022/core/guids/f6a398f13616956455e2c88f0ca1d7f5dc957d35d9ee8be18c6e44951dd16404/x86_64/repodata/repomd.xml
INFO[03-16|12:59:42] Fetching...                              URL=https://cdn.amazonlinux.com/al2022/core/guids/f6a398f13616956455e2c88f0ca1d7f5dc957d35d9ee8be18c6e44951dd16404/x86_6 …
```
> feat(amazon): fetch amazon linux 2023 CVEs

- commands/fetch-ubuntu.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
***Is this ready for review?:*** NO  
* https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/
> fix(cmd/ubuntu): fix cmd example

- README.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
***Is this ready for review?:*** NO  
* https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/
> add 3.17 in alpine

- .github/workflows/fetch.yml
- README.md
> feat(ci): add fetch test for fedora 38

- db/rdb.go
Change to use FindInBatches instead of LIMIT/OFFSET.
```console
$ make build-integration
$ make fetch-rdb
$ diff-server-rdb
```
***Is this ready for review?:*** YES  
- https://gorm.io/docs/advanced_query.html#FindInBatches
> refactor(rdb): Use FindInBatches instead of LIMIT/OFFSET

- .github/workflows/fetch.yml
- GNUmakefile
- README.md
- fetcher/ubuntu/ubuntu.go
- integration/diff_server_mode.py
add ubuntu 23.04
```console
$ goval-dictionary fetch ubuntu 23.04
INFO[04-26|23:03:38] Fetching...                              URL=https://security-metadata.canonical.com/oval/oci.com.ubuntu.lunar.cve.oval.xml.bz2
INFO[04-26|23:03:42] Fetched                                  File=oci.com.ubuntu.lunar.cve.oval.xml.bz2 Count=9507 Timestamp=2023-04-26T13:11:00
WARN[04-26|23:03:42] Failed to parse string                   timeformat="[2006-01-02 2006-01-02 15:04:05 2006-01-02 15:04:05 +0000 2006-01-02 15:04:05 UTC]" target string="2023-02-14 10:00:00 PST"
WARN[04-26|23:03:42] Failed to parse string                   timeformat="[2006-01-02 2006-01-02 15:04:05 2006-01-02 15:04:05 +0000 2006-01-02 15:04:05 UTC]" target string="2023-02-14 10:00:00 PST"
WARN[04-26|23:03:42] Failed to parse …
```
> feat(ubuntu): add ubuntu 23.04

- .github/workflows/fetch.yml
- GNUmakefile
- README.md
- integration/diff_server_mode.py
add target versions on fetch workflow
CI testing
> chore(ci/fetch): add target versions

- README.md
Based on #414 
-----
Add MariaDB in README, no code change.
Fixes # (issue)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
***Is this ready for review?:*** NO  
* https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/
> add MariaDB in README

- .github/workflows/fetch.yml
- GNUmakefile
- config/config.go
- fetcher/ubuntu/ubuntu.go
- integration/diff_server_mode.py
add 24.10
drop unavailable releases (fix: https://github.com/vulsio/goval-dictionary/actions/runs/11584874106/job/32252842677#step:7:19)
see Fetch CI Result
> feat(fetcher/ubuntu): add 24.10 and drop unavailable releases

- .github/workflows/fetch.yml
- GNUmakefile
- README.md
- config/config.go
- fetcher/ubuntu/ubuntu.go
- integration/diff_server_mode.py
> feat(fetch/ubuntu): add ubuntu 25.04

- .github/workflows/fetch.yml
update fetch version
by fetch ci
> chore(ci): update fetch version
