vulsio/goval-dictionary

- Gopkg.lock
- Gopkg.toml
- fetcher/util.go
- log/log.go
This errors occurred.
```
grouped write of manifest, lock and vendor: error while writing out vendor tree: error while exporting github.com/sirupsen/logrus: /var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/.gitignore already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/.travis.yml already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/CHANGELOG.md already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/LICENSE already exists, no checkout
/var/folders/wc/20f2d7j91rq4cvf5rz27h68h0000gn/T/dep434114490/vendor/github.com/sirupsen/logrus/README. …
```
> change logrus package name to lowercase and update other packages

- README.md
- fix typos in command usage
- fix section hierarchy
- remove trailing spaces
- some fix for markdownlint
- some misspelling fixed
> improve README documentation.

- README.md
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- commands/server.go
- config/config.go
- db/redis.go
- fetcher/util.go
- log/log.go
- main.go
1. add quiet option
2. change all output to stderr
3. add args environment
4. no output if not execute log.Initialize 
(when we used goval-dictionary's method without log.Initialize, panic occured.)
> add quiet option and args environment for AWS Lambda

- fetcher/alpine.go
- fetcher/debian.go
- fetcher/oracle.go
- fetcher/redhat.go
- fetcher/suse.go
- fetcher/ubuntu.go
Hello.
I had found a buggy behavior when specify no supported version of system distribution such like below command.
```sh
$ goval-dictionary fetch-ubuntu 17
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8437e2]
goroutine 1 [running]:
github.com/kotakanbe/goval-dictionary/vendor/github.com/cheggaaa/pb.(*Pool).Stop(0x0, 0xc42024b100, 0x0)
/home/vuls/go/src/github.com/kotakanbe/goval-dictionary/vendor/github.com/cheggaaa/pb/pool.go:76 +0x22
github.com/kotakanbe/goval-dictionary/fetcher.fetchFeedFileConcurrently(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/vuls/go/src/github.com/kotakanbe/goval-dictionary/fetcher/util.go:100 +0xb1d
github.com/kotakanbe/goval-dictionary/fetcher.FetchUbuntuFiles(0xc42026 …
```
> Fix a panic when specify no supported version

- models/models.go
An error occurred while inserting OVAL feed of RedHat 7 into MySQL.
```
}, err: Error 1406: Data too long for column 'description' at row 1
```
> fix: change gorm column size of Definition>Description

- models/redhat.go
In the following case, goval-dictionary fails to insert CVE information to `cves` table (no `cve` tag under `advisory` tag).
```
<advisory from="secalert@redhat.com">
<severity>Important</severity>
<rights>Copyright 2018 Red Hat, Inc.</rights>
<issued date="2018-01-03"/>
<updated date="2018-01-03"/>
<bugzilla href="https://bugzilla.redhat.com/1519778" id="1519778">CVE-2017-5753 hw: cpu: speculative execution bounds-check bypass</bugzilla>
<bugzilla href="https://bugzilla.redhat.com/1519780" id="1519780">CVE-2017-5715 hw: cpu: speculative execution branch target injection</bugzilla>
<bugzilla href="https://bugzilla.redhat.com/1519781" id="1519781">CVE-2017-5754 hw: cpu: speculative execution permission faults handling</bugzilla>
<affected_cpe_list> …
```
> fix(redhat): occasionally no cve tag in advisory tag of RedHat OVAL

- .gitignore
- .goreleaser.yml
- .travis.yml
After Travis is configured with the GitHub token, this will automatically publish binaries.
See https://github.com/future-architect/vuls/pull/460 and https://github.com/kotakanbe/go-cve-dictionary/pull/75#issuecomment-377140104
> Add goreleaser to distribute binaries

- README.md
- commands/fetch-alpine.go
- commands/fetch-amazon.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- commands/server.go
- util/util.go
add  log-json option
`goval-dictionary fetch-amazon --log-json`
- stderr
```
{"URL":"https://alas.aws.amazon.com/alas.rss","lvl":"info","msg":"Fetching... ","t":"2018-04-26T15:00:17.693635644+09:00"}
{"lvl":"info","msg":"Finished to fetch OVAL definitions.","t":"2018-04-26T15:00:20.001944237+09:00"}
{"lvl":"info","msg":"987 CVEs","t":"2018-04-26T15:00:20.051298561+09:00"}
```
- logfile
```
{"lvl":"crit","msg":"\n\t\tUsage:\n\t\tselect OVAL by package name\n\t\t./goval-dictionary select -by-package RedHat 7 java-1.7.0-openjdk\n\n\t\tselect OVAL by CVE-ID\n\t\t./goval-dictionary select -by-cveid RedHat 7 CVE-2015-1111\n\t\t","t":"2018-04-26T14:58:13.792731578+09:00"}
{"err":"Unknown OS Type: bash","lvl":"eror","msg":"Failed to new db.","t":"2018-04-26T14:58:13.793255945+09:00"} …
```
> add log-json option

- db/redis.go
- models/oracle.go
1. `vuls report` returns different result each time in the case of Oracle Linux
2. False Negative (Oracle Linux)
> fix(oracle): vuls report returns different result each time in the case of Oracle Linux

- models/ubuntu.go
- models/ubuntu_test.go
OVAL format for Ubuntu has been changed.
Older versions of goval-dictionary cannot parse the new format of OVAL.
This cause the Uubntu scan results in Vuls is zero.
see  https://github.com/future-architect/vuls/issues/816
Vuls users who are scanning Ubuntu Linux have to update goval-dictionary.
> fix(ubuntu): Support latest OVAL format for Ubuntu

- README.md
- config/config.go
- fetcher/ubuntu.go
I believe this change should allow support for Ubuntu 19/ Disco Dingo.  OVAL data is published and available at the standard URL scheme for this version.
> Support Ubuntu 19

- db/rdb/alpine.go
- db/rdb/debian.go
- db/rdb/rdb.go
- db/rdb/rdb_test.go
- db/rdb/ubuntu.go
- before 
```foreever```
- after
```0.26s```
> refactor(alpine): Query tuning

- README.md
- commands/fetch-amazon.go
- commands/fetch-oracle.go
- models/amazon.go
```
$ cat amazon2.jzon | jq . 
{
"Family": "amazon",
"Release": "2 (Karoo)",
"RunningKernel": {
"Release": "4.14.121-109.96.amzn2.x86_64",
"Version": ""
},
"Packages": {
"kernel": {
"Name": "kernel",
"Version": "4.14.114",
"Release": "105.126.amzn2",
"Arch": "x86_64"
},
"dracut": {
"Name": "dracut",
"Version": "033",
"Release": "535.amzn2.1.2",
"Arch": "x86_64"
}
}
}
```
```
$ : check init redis size 
$ redis-cli info  | grep used_memory_human 
used_memory_human:833.74K
$ : fetch amazon linux oval
$ ./goval-dictionary fetch-amazon -dbtype=redis -dbpath=redis://localhost:6379
$ redis-cli info  | grep used_memory_human 
used_memory_human:39.46M
$ curl -X POST -H "Content-Type: application/json" -d @amazon2.json http://localhost:5515/vuls
[Jun 25 14:30:22]  INFO [localhost] : 0 CVEs are …
```
> Add no-details for fetch-amazon 

- server/server.go
Vuls in server mode calls the goval component with an optional arch param, so goval must support an url endpoint without this param.
Else following error when vuls generates a json report:
"Failed to fill with OVAL: Failed to fetch OVAL. err: [%!w(*xerrors.errorString)] "
> Vuls in server mode: arch param is optional for goval

- commands/fetch-debian.go
- models/debian.go
Add no details command for debian.
```
$  ./goval-dictionary fetch-debian -dbtype redis -dbpath redis://localhost:6379/1 7 8 9
$ redis-cli -c info memory  | grep used_memory_human
used_memory_human:38.24M
$  ./goval-dictionary fetch-debian --no-details -dbtype redis -dbpath redis://localhost:6379/1 7 8 9
$ redis-cli -c info memory  | grep used_memory_human
used_memory_human:26.15M
```
> Add debian no details option for debian.

- README.md
- config/config.go
- fetcher/ubuntu.go
- go.sum
- Fetch OVAL data on Ubuntu20.04
#84 is reference issue
- config.go
- add code name of ubuntu20.04
- ubuntu.go
- add case ubuntu20.04
- Readme.md
- Add to use fetch OVAL data on Ubuntu 20.04
Created oval.sqlite3
Check oval.sqlite3
> Support ubuntu20.04

- fetcher/alpine.go
use the new alpine secdb resource
the current one is deprecated
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes # (issue)
https://github.com/kotakanbe/goval-dictionary/issues/93
fetched alpine 3.12
> Use new alpine secdb resource

- README.md
- commands/fetch-ubuntu.go
- config/config.go
- fetcher/ubuntu.go
- Fix an error whene we get OVAL data of Ubuntu19
- Unsupport to get OVAL data of Ubuntu12, 17
- Because end of life ubuntu12,17 (If you want to know detail, please check reference URL)
Fixes #91 
- Using ```goval-dictionary fetch-ubuntu 19```
- Using ```goval-dictionary fetch-ubuntu unsupported version```
https://wiki.ubuntu.com/Releases
> Fix get ubuntu oval data

- config/config.go
- db/rdb/rdb.go
- db/redis.go
OVAL uses Debian when family is Raspbian.
Fixes https://github.com/future-architect/vuls/issues/1001
The test result confirms the use of OVAL in this PR.
https://github.com/future-architect/vuls/pull/1019
***Is this ready for review?:*** YES  
- https://github.com/future-architect/vuls/issues/1001
- https://github.com/future-architect/vuls/pull/1019
> change Raspbian use Debian OVAL

- README.md
- commands/select.go
The contents changed in 0e718b4 were not applied to README.md and argument check, so it was corrected.
Fixes #97 
I ran the following command.
Since there is much CVE information on chromium, it is omitted.
```bash
$ ./goval-dictionary select -by-package debian 10 chromium x86_64
...
models.Definition{
ID:           0x3ff9,
RootID:       0x1,
DefinitionID: "oval:org.debian:def:20206504",
Title:        "CVE-2020-6504",
Description:  "Insufficient policy enforcement in notifications in Google Chrome prior to 74.0.3729.108 allowed a remote attacker to bypass notification restrictions via a crafted HTML page.",
Advisory:     models.Advisory{
ID:              0x0,
DefinitionID:    0x0,
Severity:        "",
Cves:            []models.Cve{},
Bugzillas:       []models.Bugzilla{},
AffectedCPEList: …
```
> fix select command arguments

- util/util.go
Prevented the program from terminating in a panic if permission error occurs when goval-dictionary writes to the log file.
Fixes #83 
- Permission set 400 of /var/log/vuls
- exec goval-dictionary fetch-ubuntu 20
* https://github.com/kotakanbe/go-cve-dictionary/blob/master/log/log.go
> Fix terminated in a panic when permission error 

- commands/fetch-suse.go
command "goval fetch-suse" for SLES is not working
When using 
`goval-dictionary fetch-suse -suse-enterprise-server 12`
OVALs are downloaded from suse website but then i  got "Unsuport family: opensuse" message when inserting then in the database, like #100 and #86 issues
after this change i was able to fetch sles OVALs and was also able to use vuls to analyze SLES vulnerabilities (I'll open an issue to document it on vuls side after)
Fixes #100 #86 (at least I think ;) )
After the fix I can now fetch ovals for SLES 11 12 and 15 
```
goval-dictionary fetch-suse -suse-enterprise-server 11
goval-dictionary fetch-suse -suse-enterprise-server 12
goval-dictionary fetch-suse -suse-enterprise-server 15
```
And I can check packages on my sles system by …
> Use detected SuSE type instead of opensuse when inserting oval data

- db/rdb/rdb.go
- db/rdb/suse.go
I don't know since when, but SLES OVAL is provided for each major version instead of major.minor.
http://ftp.suse.com/pub/projects/security/oval/
I scanned and report SLES15.2, and got the following error.
```
[Sep 28 16:04:37]  INFO [localhost] sles: 0 CVEs are detected with Library
[Sep 28 16:04:37] ERROR [localhost] Failed to fill with OVAL: OVAL entries of suse.linux.enterprise.server 15.2 are not found. Fetch OVAL before reporting. For details, see `https://github.com/kotakanbe/goval-dictionary#usage`
```
> fix(suse): OVAL for SLES provided in earch major version

- .github/workflows/golangci.yml
- db/redis.go
Fixes #107 
before
```
./goval-dictionary   fetch-debian  -debug  -dbtype redis -dbpath "redis://localhost/0" 9
DBUG[11-18|07:16:09] Opening DB.                              db=redis
INFO[11-18|07:16:09] Fetching...                              URL=https://www.debian.org/security/oval/oval-definitions-stretch.xml
INFO[11-18|07:16:12] Fetched...                               URL=https://www.debian.org/security/oval/oval-definitions-stretch.xml
INFO[11-18|07:16:12] Finished fetching OVAL definitions 
INFO[11-18|07:16:15] Fetched                                  URL=https://www.debian.org/security/oval/oval-definitions-stretch.xml OVAL definitions=22871
INFO[11-18|07:16:17] Total CVE-IDs:                           count=16523
```
after
```
go build; and ./goval-dictionary   fetch-debian …
```
> fix(debian): use Debian.CveID when refs is empty #107

- db/rdb/alpine.go
- db/rdb/debian.go
A false negative in Debian's kernel vulnerability has been fixed.
In Debian's OVAL, kernel vulnerabilities are defined as "linux".
Due to a bug in the RDB oval driver, no more than 998 vulnerabilities were obtained.
cve-ids related "linux" defined after 999 was not possible to detect.
This bug affects the case of RDB backend with scanning Debian.
before
```
sqlite3
[Nov 18 08:30:15]  INFO [localhost] deb9: 6 CVEs are detected with OVAL
redis
[Nov 18 08:31:08]  INFO [localhost] deb9: 48 CVEs are detected with OVAL
```
after
```
sqlite3
[Nov 18 09:28:23]  INFO [localhost] deb9: 48 CVEs are detected with OVAL
```
> fix(debian): false negative of kernel cves with rdb backend

- db/rdb/alpine.go
- db/rdb/debian.go
Oval definitions are not refreshed when fetching Debian OVALs. First fetch if correct and data are correctly inserted but if you run `goval-dictionary fetch-debian 10` later, nothing is update. Date of definitions is still the same (leading to a warning telling that OVAL definitions/roots are outdated) and data are not inserted. 
I noted that debian insertion is different from other systems, and we could apply the same logic here than other systems.
With this PR, I can now detect new CVE on debian, and the definitions are updated accordingly 
I'm running a Vuls instance and now i can detect updated CVE on debian systems, and i don't have OVAL Definitions outdated message anyore
***Is this ready for review?:*** YES  
* …
> Debian oval definitions are not updated

- models/ubuntu.go
- models/ubuntu_test.go
Hey there,
Please feel free to correct me if I'm wrong here as I'm new to this but deferred packages should be affected, no?
for example I used the Ubuntu 18 OVAL  and specifically: 
`<definition class="vulnerability" id="oval:com.ubuntu.bionic:def:2018208390000000" version="1">`
Which has the criteria: 
`<criterion test_ref="oval:com.ubuntu.bionic:tst:2018208390000000" comment="systemd package in bionic is affected, but a decision has been made to defer addressing it." />`
and it does not pass the not decided regex:
```go
var reNotDecided = regexp.MustCompile(`^(.+) package in .+ is affected, but a decision has been made to defer addressing it  .+$`)
```
So I changed the RE to catch the shown case above.
I hope my understanding here is correct.
Thanks!
Please delete options that are not …
> fix(ubuntu): Fix deferred packages not showing as affected

- commands/select.go
- db/rdb/oracle.go
- models/models.go
- models/oracle.go
- server/server.go
OVAL fetch for Oracle had previously ignored Arch, which caused false positives in Vuls.
"CVE-2011-1079"
When I scan Oracle Linux7 on x86_64, the following are detected.
```
"CVE-2011-1079": {
"affectedPackages": [
{
"name": "python-perf",
"notFixedYet": true,
"fixState": "Not fixed yet",
"fixedIn": "0:4.14.35-1902.2.0.el7uek"
}
]
```
It is correct that this only detects aarch64, and should not be detected on x86_64.
```
<criterion test_ref="oval:com.oracle.elsa:tst:20194685001" comment="Oracle Linux 7 is installed"/>
<criteria operator="OR">
<criteria operator="AND">
<criterion test_ref="oval:com.oracle.elsa:tst:20194685002" comment="Oracle Linux arch is aarch64"/>
...
<criterion test_ref="oval:com.oracle.elsa:tst:20194685021" comment="python-perf is earlier than …
```
> fix(oracle): collect arch info in OVAL

- models/alpine.go
- models/amazon.go
- models/debian.go
- models/models.go
- models/oracle.go
- models/ubuntu.go
Fixes #80 
Inserting 0000-00-00 into datetime is not a good idea in MySQL.
ref: https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sqlmode_no_zero_date
So this PR solves this problem by filling the datetime with the lower limit of the range supported by MySQL. Also, the problem of overflow in Oracle has been resolved.
```console
// SQLite3
$ sqlite3 --version
3.31.1 2020-01-27 19:55:54 3bfa9cc97da10598521b342961df8f5f68c7388fa117345eeb516eaa837balt1
$ goval-dictionary fetch-debian 7 8 9 10
$ goval-dictionary fetch-ubuntu 14 16 18 19 20
$ goval-dictionary fetch-oracle
$ goval-dictionary fetch-amazon
$ goval-dictionary fetch-alpine 3.3 3.4 3.5 3.6
// MySQL
$ mysql --version
mysql  Ver 8.0.25-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
$ goval-dictionary fetch-debian --dbtype=mysql …
```
> fix(mysql): fix incorrect datetime value at fetch cmd

- models/ubuntu.go
The CVE ID may become "" in Ubuntu's ConvertUbuntuToModel, which is not affected in Redis due to the following location, but is still inserted in RDB.
https://github.com/kotakanbe/goval-dictionary/blob/b84c78b96673bf95945cd7daded7593a4b96c834/db/redis.go#L206-L208
This will cause a difference in the server mode response between Redis and RDB.
For example, in the Ubuntu 14 environment, the response to mysql-5.5 in RDB and Redis will look like the following file. The difference is the inclusion of the following OVAL definition.
[rdb_585b989.json.txt](https://github.com/kotakanbe/goval-dictionary/files/6635556/rdb_585b989.json.txt)
[redis_585b989.json.txt](https://github.com/kotakanbe/goval-dictionary/files/6635557/redis_585b989.json.txt)
```json
{
"DefinitionID": …
```
> fix(ubuntu): do not register anything with an unknown CVE ID

- db/rdb/rdb.go
Under a very low load of vuls scans (4 scans in parallel) a race condition occurs and makes the program crash
Stack trace :
```
fatal error: concurrent map writes
goroutine 70637 [running]:
runtime.throw(0xb58f0f, 0x15)
/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0008c7430 sp=0xc0008c7400 pc=0x43de92
runtime.mapassign_faststr(0xaae560, 0xc0005c2000, 0xb4f678, 0x6, 0x1)
/usr/local/go/src/runtime/map_faststr.go:211 +0x3f1 fp=0xc0008c7498 sp=0xc0008c7430 pc=0x41c091
github.com/kotakanbe/goval-dictionary/db/rdb.(*Driver).NewOvalDB(0xc0008da000, 0xc0007f8132, 0x6, 0x3e, 0x94)
/go/src/github.com/kotakanbe/goval-dictionary/db/rdb/rdb.go:76 +0x87c fp=0xc0008c7548 sp=0xc0008c7498 pc=0x888f9c
github.com/kotakanbe/goval-dictionary/db/rdb.NewRDB(0xc0007f8132, 0x6, 0xb5009a, 0x7, …
```
> thread safety : prevent a race condition in the RDMS driver (sqlite, mysql, postgresql)

- .gitignore
- GNUmakefile
- integration/diff_server_mode.py
To make it easy to check with your favorite diff tool.
```
$ vimdiff ./integration/diff/CVE-2003-0689.*
```
When testing integration, delete `./integration/diff`, and then retest.
```
$ pkill -KILL goval-dict.old ; pkill -KILL goval-dict.new; ps aux | grep goval; rm integration/diff/*; make diff-server-rdb-redis
```
> chore(integration-test): Output json files when diff under ./integration/diff

- commands/fetch-alpine.go
- commands/fetch-amazon.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
If an error occurs during the first fetch, it is required to clean the DB during the second Insert. 
The old data can be deleted when updating between the same schema versions.
To avoid this problem, insert FetchMeta first.
> fix(db): change fetchmeta insert order

- commands/fetch-alpine.go
- commands/fetch-amazon.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/server.go
- db/db.go
- db/rdb.go
- db/redis.go
- fetcher/alpine.go
- fetcher/amazon.go
- fetcher/debian.go
- fetcher/oracle.go
- fetcher/redhat.go
- fetcher/suse.go
- fetcher/ubuntu.go
- fetcher/util.go
- models/models.go
- server/server.go
goval-dictionary does not have a force option, so we could not force the OVAL to be updated. I thought about adding a force option or removing the skip scheme, but decided to remove the skip.
***Is this ready for review?:*** NO
> feat: do not skip OVAL insert

- db/redis.go
>Failed to detect CVE with OVAL: Failed to get ubuntu OVAL info by package: oval.request{packName:&#34;linux-aws&#34;, versionRelease:&#34;5.4.0-1037.39~18.04.1&#34;, newVersionRelease:&#34;&#34;, arch:&#34;&#34;, binaryPackNames:[]string(nil), isSrcPack:false, modularityLabel:&#34;&#34;}, err: Failed to HMGet. err: Some fields do not exist. defIDs: [&#34;oval:com.ubuntu.bionic:def:201922140000000&#34; &#34;oval:com.ubuntu.bionic:def:201513500000000&#34; &#34;oval:com.ubuntu.bionic:def:2019148350000000&#34; 
> fix(redis): Failed to detect CVE with OVAL: Failed to get ubuntu OVAL info by package

- .github/workflows/golangci.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
- .github/workflows/tidy.yml
- .goreleaser.yml
- commands/fetch-debian.go
- go.mod
- go.sum
- models/suse.go
Debian's OVAL XML files have suddenly changed to ASCII encoding.
xml.Unmarshal does not support anything other than UTF-8, so this has been fixed.
Duplicate PR: https://github.com/vulsio/goval-dictionary/pull/171
```console
$ goval-dictictionary fetch debian 9
INFO[12-07|15:50:35] Fetching...                              URL=https://www.debian.org/security/oval/oval-definitions-stretch.xml
INFO[12-07|15:50:38] Fetched...                               URL=https://www.debian.org/security/oval/oval-definitions-stretch.xml
INFO[12-07|15:50:38] Finished fetching OVAL definitions 
Failed to unmarshal xml. url: https://www.debian.org/security/oval/oval-definitions-stretch.xml, err: xml: encoding "ASCII" declared but Decoder.CharsetReader is nil
$ goval-dictictionary fetch debian 10 …
```
> fix(fetch/debian): fix unmarshal xml

- .golangci.yml
- .revive.toml
- GNUmakefile
- commands/fetch-alpine.go
- commands/fetch-amazon.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- commands/server.go
- db/db.go
- db/rdb.go
- db/redis.go
Change the linter to revive, since golint has been deprecated as follows.
> NOTE: Golint is deprecated and frozen. There's no drop-in replacement for it, but tools such as Staticcheck and go vet should be used instead.
```console
$ make lint
$ golangci-lint run -c .golangci.yml
```
> chore(linter): change linter from golint to revive

- models/debian.go
- models/ubuntu.go
Debian used to have a title format of `"CVE-ID"`, but this has recently been changed to `"DSA-ID"` for Debian 7 and 8, and to `"CVE-ID PackageName"` for Debian 9, 10 and 11.
So Debian uses the `source="CVE"` information in References as cves.
Also, Ubuntu used to get CVEID by parse title, but to avoid this problem, get it from references.
Fixes #167
```console
$ goval-dictionary fetch debian 8
$ sqlite3 oval.sqlite3
sqlite> SELECT * FROM cves LIMIT 3;
id|advisory_id|cve_id|cvss2|cvss3|cwe|impact|href|public
1|1|||||||
2|2|||||||
3|3|||||||
$ goval-dictionary fetch debian 11
$ sqlite3 oval.sqlite3
sqlite> SELECT * FROM cves LIMIT 3;
id|advisory_id|cve_id|cvss2|cvss3|cwe|impact|href|public
1|1|CVE-1999-0199 glibc|||||https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-1999-0199 glibc| …
```
> feat(fetch): use CVE information in references

- db/redis.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 
Fixes #173 
```console
// setup
$ redis-cli -p 6379
127.0.0.1:6379> SMEMBERS OVAL#debian#11#PKG#a2ps
1) "oval:org.debian:def:75476148081331502013618590951901882535"
2) "oval:org.debian:def:test" // missing defID
3) "oval:org.debian:def:88988697754130173838013832986587830139"
4) "oval:org.debian:def:89135559689250371593682731796707320194"
5) "oval:org.debian:def:287503723613106787615900001340040093915"
6) "oval:org.debian:def:205400728072744866719207044776762665715"
// startup goval-dictionary server
$ goval-dictionary server --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
// search debian 11 a2ps package
$ curl http://127.0.0.1:1324/packs/debian/11/a2ps | jq .
// …
```
> feat(redis): delete missing defID field in Sets

- GNUmakefile
- db/redis.go
There was a bug in the update method of deleting outdated information in the DB at the time of Redis fetch, causing more information than necessary to be deleted.This bug has been fixed.
This is a bug related to #173, as it will break the key relationship in Redis.
```console
$ goval-dictionary fetch debian 11 --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
$ redis-cli -p 6379
127.0.0.1:6379> SMEMBERS OVAL#debian#11#CVE#CVE-2021-22204
1) "oval:org.debian:def:100020194192621893181231895146832483613"
127.0.0.1:6379> HGET OVAL#debian#11#DEF oval:org.debian:def:100020194192621893181231895146832483613
"{\"DefinitionID\":\"oval:org.debian:def:100020194192621893181231895146832483613\",\"Title\":\"CVE-2021-22204 libimage-exiftool-perl\",\"Description\":\"Improper neutralization of user data in …
```
> fix(redis): update Redis key relationship successfully

- fetcher/amazon.go
The URL of mirror.list in Amazon Linux 2022 has been changed.
Since the immutable URL indicating latest is unknown, every time the URL is changed, I have to change the URL as in this pull request.
If anyone knows the immutable URL that shows the latest of the mirror.list of Amazon Linux 2022, please let me know.
```
curl https://al2022-repos-us-east-1-9761ab97.s3.dualstack.us-east-1.amazonaws.com/core/guids/cdf9aafeacc2e5e1b39d59842558a197a28da245b7eaee4775741ba275d2a08c/x86_64/repodata/updateinfo.xml.gz | gunzip | less
```
> fix(amazon): change mirror.list URL of AL2022

- commands/fetch-alpine.go
- commands/fetch-amazon.go
- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- commands/select.go
- commands/server.go
- db/rdb.go
- db/redis.go
- models/models.go
Add the time when the fetch is completed to fetchmeta.
```console
$ goval-dictionary fetch debian 11
$ sqlite3 oval.sqlite3  
sqlite> SELECT last_fetched_at FROM fetch_meta;
2021-12-26 09:59:50.637731453+09:00
$ goval-dictionary fetch debian 11
$ sqlite3 oval.sqlite3  
sqlite> SELECT last_fetched_at FROM fetch_meta;
2021-12-26 10:00:09.584155161+09:00
```
```console
$ redis-cli -p 6379
127.0.0.1:6379> HGET OVAL#FETCHMETA LastFetchedAt
(nil)
$ goval-dictionary fetch debian 11 --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
$ redis-cli -p 6379
127.0.0.1:6379> HGET OVAL#FETCHMETA LastFetchedAt
"2021-12-26T10:00:32.020588113+09:00"
$ goval-dictionary fetch debian 11 --dbtype redis --dbpath "redis://127.0.0.1:6379/0"
$ redis-cli -p 6379
127.0.0.1:6379> HGET OVAL#FETCHMETA LastFetchedAt …
```
> feat(db): add LastFetchedDate in fetchmeta

- fetcher/amazon.go
- fetcher/util.go
UpdateInfo for Amazon Linux 2022 was implemented in the pull request #169 #191 ,
But it was not designed to get the latest version of UpdateInfo.
Therefore, it was necessary to change the URL every time the base image was upgraded.
We found a way to show the latest version of UpdateInfo and implemented it. 
(Thanks for the info @wagde-orca )
```
curl https://al2022-repos-us-west-2-9761ab97.s3.dualstack.us-west-2.amazonaws.com/core/releasemd.xml |less
```
xml
```
<?xml version="1.0" encoding="utf8"?>
<root>
<releases>
<release version="2022.0.20211118">
<update>
<name>2022.0.20211124</name>
<version_string>2022.0.20211124</version_string>
<release_notes>https://aws.amazon.com</release_notes>
</update>
<update>
<name>2022.0.20211201</name>
<version_string>2022.0.20211201</version_string> …
```
> feat(al2022): fetch the latest updateInfo for al2022

- README.md
- fetcher/ubuntu.go
Fixes #190 
It seems that we can fetch information about new CVEs by changing the URL of OVAL.
This is the case of CVE-2021-4034 that we encountered.
```console
$ date
Fri 28 Jan 22:01:09 JST 2022
$ goval-dictionary.master version
goval-dictionary v0.6.0 b6263e5
$ goval-dictionary.master fetch ubuntu 20
$ goval-dictionary.master select --by-cveid ubuntu 20 CVE-2021-4034
------------------
[]models.Definition{}
$ goval-dictionary.pr version
goval-dictionary v0.6.0 23e2856
$ goval-dictionary.pr fetch ubuntu 20
$ goval-dictionary.pr select --by-cveid ubuntu 20 CVE-2021-4034
CVE-2021-4034 on Ubuntu 20.04 (focal) - high.
[{7853 7854 CVE-2021-4034     https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-4034 }]
------------------
[]models.Definition{
models.Definition{
ID:           0x1eae, …
```
> fix(ubuntu): change OVAL URL

- db/rdb.go
fix syntax error in query.
Fixes https://github.com/future-architect/vuls/issues/1357
```console
$ goval-dictionary fetch debian --dbtype=postgres --dbpath="postgresql://mainek00n:password@localhost:5432/oval" 11
$ goval-dictionary.master server --dbtype=postgres --dbpath="postgresql://mainek00n:password@localhost:5432/oval"
INFO[01-24|02:19:26] Starting HTTP Server... 
INFO[01-24|02:19:26] Listening...                             URL=127.0.0.1:1324
____    __
/ __/___/ /  ___
/ _// __/ _ \/ _ \
/___/\__/_//_/\___/ v4.6.3
High performance, minimalist Go web framework
https://echo.labstack.com
____________________________________O/_______
O\
⇨ http server started on 127.0.0.1:1324
EROR[01-24|02:19:40] Failed to get by Package Name.           err="ERROR: syntax error at or near \".\" …
```
> fix(rdb): change where query

- commands/fetch-debian.go
- commands/fetch-oracle.go
- commands/fetch-redhat.go
- commands/fetch-suse.go
- commands/fetch-ubuntu.go
- fetcher/util.go
Changed to show Warn message if the file hasn't been updated for 3 days.
This will allow us to notice if the OVAL URL has been changed.
- Warn
```
INFO[01-29|08:16:04] Fetching...                              URL=https://www.debian.org/security/oval/oval-definitions-buster.xml
INFO[01-29|08:16:09] Fetched                                  File=oval-definitions-buster.xml Count=23064 Timestamp=2022-01-28T19:31:40.188-04:00
WARN[01-29|08:16:09] The fetched OVAL has not been updated for 3 days, the OVAL URL may have changed, please register a GitHub issue. GitHub=https://github.com/vulsio/goval-dictionary/issues OVAL=https://www.debian.org/security/oval/oval-definitions-buster.xml Timestamp=2022-01-28T19:31:40.188-04:00
INFO[01-29|08:16:09] Refreshing... …
```
> feat(fetch): show timestamps of fetched OVAL files and warn if it hasn't been updated in 3 days

- fetcher/util/util_test.go
- models/suse/suse.go
- models/suse/suse_test.go
Recognize `SUSE Manager` as an OS, not as a Package, and do not Insert it into the DB.
Also, do not insert `SUSE Enterprise Micro`, `SUSE Enterprise Storage` that has been inserted as SUSE Enterprise Server (Desktop).
```console
$ goval-dictionary fetch suse --suse-type suse-enterprise-server 15 2>/dev/null
$ sqlite3 oval.sqlite3 "SELECT COUNT(name) FROM packages WHERE name = 'SUSE-Manager-Proxy-release';"
188600
$ sqlite3 oval.sqlite3 "SELECT * FROM roots;"
1|suse.linux.enterprise.server|15.4|2022-03-14 13:53:17.804896628+09:00
2|suse.linux.enterprise.server|5.1|2022-03-14 13:53:17.937815186+09:00 // SUSE Enterprise Micro
3|suse.linux.enterprise.server|15.1|2022-03-14 13:53:18.044831984+09:00
4|suse.linux.enterprise.server|15.2|2022-03-14 13:53:23.651155612+09:00 …
```
> fix(suse): not recognizing SUSE Manager as Package

- db/rdb.go
When inserting packages that exceed `--batch-size`, after the second round of loop, some packages failed to set their definition_id because they were not done for packages in the range `idx2.From + i`.
https://github.com/vulsio/goval-dictionary/blob/master/db/rdb.go#L307-L309
Therefore, when deleting, the DB space was increased because it was not possible to delete the Package that was supposed to be bound to the Definition. There is also a problem that data that should have been displayed when searching was not displayed.
```console
$ goval-dictionary fetch amazon 2>/dev/null && ll oval.sqlite3
-rw-r--r-- 1 mainek00n mainek00n 9.2M Mar 14 12:15 oval.sqlite3
$ sqlite3 oval.sqlite3 "SELECT COUNT(definition_id) FROM packages WHERE definition_id = 0;"
17601
$ goval-dictionary fetch amazon …
```
> fix(rdb): misconfigured index in package

- GNUmakefile
- README.md
- config/config.go
- fetcher/ubuntu/ubuntu.go
- integration/diff_server_mode.py
Ubuntu 22.04 will be released on April 21.
OVAL is also available for 22.04, which can be fetched.
OVAL URL: https://security-metadata.canonical.com/oval/com.ubuntu.jammy.cve.oval.xml.bz2
```console
$ goval-dictionary fetch ubuntu 22
INFO[04-25|11:38:19] Fetching...                              URL=https://security-metadata.canonical.com/oval/com.ubuntu.jammy.cve.oval.xml.bz2
INFO[04-25|11:38:20] Fetched                                  File=com.ubuntu.jammy.cve.oval.xml.bz2 Count=1 Timestamp=2022-04-25T01:47:04
INFO[04-25|11:38:20] Refreshing...                            Family=ubuntu Version=22
INFO[04-25|11:38:20] Inserting new Definitions... 
1 / 1 [----------------------------------------------------------] 100.00% ? p/s
INFO[04-25|11:38:20] Finish …
```
> feat(ubuntu): add Jammy Jellyfish(22.04)

- .github/workflows/golangci.yml
- .github/workflows/goreleaser.yml
- .github/workflows/test.yml
- .golangci.yml
- Dockerfile
- GNUmakefile
- db/rdb.go
- db/redis.go
- go.mod
- go.sum
- models/alpine/alpine.go
- models/suse/suse_test.go
- server/server.go
fix lint errors.
```console
$ golangci-lint version
golangci-lint has version v1.45.2 built from (unknown, mod sum: "h1:9I3PzkvscJkFAQpTQi5Ga0V4qWdJERajX1UZ7QqkW+I=") on (unknown)
$ golangci-lint run -c .golangci.yml
WARN [linters context] staticcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
$ make test
```
> chore: fix lint error

- models/amazon/amazon.go
- models/debian/debian.go
- models/fedora/fedora.go
- models/redhat/redhat.go
- models/ubuntu/ubuntu.go
- models/util/util.go
- models/util/util_test.go
Multiple layouts are accepted when parsing time.
```console
$ goval-dictionary fetch ubuntu 14 16 18 19 20 21 22
INFO[05-10|13:16:00] Fetching...                              URL=https://security-metadata.canonical.com/oval/com.ubuntu.bionic.cve.oval.xml.bz2
INFO[05-10|13:16:00] Fetching...                              URL=https://people.canonical.com/~ubuntu-security/oval/com.ubuntu.eoan.cve.oval.xml.bz2
INFO[05-10|13:16:00] Fetching...                              URL=https://security-metadata.canonical.com/oval/com.ubuntu.focal.cve.oval.xml.bz2
INFO[05-10|13:16:00] Fetching...                              URL=https://security-metadata.canonical.com/oval/com.ubuntu.hirsute.cve.oval.xml.bz2
INFO[05-10|13:16:00] Fetching... …
```
> feat: support multi layout

- .github/workflows/docker-build.yml
I fixed that `version` sub-command doesn't print version and reivsion with docker container.
This problem is implemented at v0.4.0 (when GAdocker is first implemented).
```
$ docker run -it --rm vuls/goval-dictionary:latest version
goval-dictionary
$ docker run --rm vuls/goval-dictionary:0.3.5 -v
goval-dictionary v0.3.5 0a1e75f
$ docker run --rm vuls/goval-dictionary:v0.4.0 -v
goval-dictionary
```
With GitHub Actions docker build, version and revision couldn't specified because no `.git` in build context.
```
#0 0.097 fatal: not a git repository (or any of the parent directories): .git
#18 0.099 fatal: not a git repository (or any of the parent directories): .git
#18 0.101 fatal: not a git repository (or any of the parent directories): .git
```
cf. …
> fix(GAdocker): version sub-command doesn't print version and revision

- commands/fetch-ubuntu.go
- models/ubuntu/types.go
- models/ubuntu/ubuntu.go
- models/ubuntu/ubuntu_test.go
The Ubuntu Fixed Package is for cases that match the following regular expressions.
https://github.com/vulsio/goval-dictionary/blob/8e6c8e373369934adedce93ef6e0f940db342513/models/ubuntu/ubuntu.go#L154-L175
This definition and [CVE-2022-28289 - Security Tracker](https://ubuntu.com/security/CVE-2022-28289) will explain the two cases of matching regular expressions.
```xml
<definition class="vulnerability" id="oval:com.ubuntu.jammy:def:2022282890000000" version="1">
<metadata>
<title>CVE-2022-28289 on Ubuntu 22.04 LTS (jammy) - medium.</title>
<reference source="CVE" ref_id="CVE-2022-28289" ref_url="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28289" />
<advisory>
<ref>https://ubuntu.com/security/CVE-2022-28289</ref>
</advisory>
</metadata>
<criteria>
<extend_definition …
```
> refactor(ubuntu): change criterion walk

- commands/root.go
- fetcher/fedora/fedora.go
Support for fetch in the archived version of Fedora.
Also, restore the `--log-to-file` flag.
Fixes #233, #236
```console
$ goval-dictionary fetch fedora 32 33 --log-to-file --log-json --log-dir .
$ cat ./goval-dictionary.log | jq .msg | grep "CVEs for Fedora"
"240 CVEs for Fedora 32. Inserting to DB"
"263 CVEs for Fedora 33. Inserting to DB"
```
> fix(fedora): support archive version

- fetcher/fedora/fedora.go
update fedora archive version.
```console
$ goval-dictionary fetch fedora 35
INFO[02-08|11:05:58] start fetch data from repomd.xml of non-modular package 
INFO[02-08|11:05:58] Fetching...                              URL=https://dl.fedoraproject.org/pub/fedora/linux/updates/35/Everything/x86_64/repodata/repomd.xml
Failed to fetch files. err: fetchEverythingFedora. err: Failed to fetch feed file, err: Failed to fetch. err: [Failed to write to output stream: Expected HTTP Status 200, received: "404 Not Found"]
```
```console
$ goval-dictionary fetch fedora 35
INFO[02-08|11:09:00] start fetch data from repomd.xml of non-modular package 
INFO[02-08|11:09:00] Fetching...                              URL=https://archives.fedoraproject.org/pub/archive/fedora/linux/updates/35/Everything/x86_64/rep …
```
> fix(fedora): update archive version

- .github/workflows/fetch.yml
* Automated integration testing for feed consumers and Postgres DB
* Runs on push and Sunday at midnight
* run locally with `make test-integration`
Wrote integration tests. Clone repo and run `make test-integration`, or see GH actions.
> test: add integration testing for OVAL

- db/redis.go
When the Insert update process was broken, these PRs(https://github.com/vulsio/goval-dictionary/pull/164, https://github.com/vulsio/goval-dictionary/pull/175) implemented log output and the removal of the definition ID that caused the error, thus avoiding the constant errors.
The bug in the Insert update process should have been fixed in this PR(https://github.com/vulsio/goval-dictionary/pull/177).
This should be an error because the Redis relation may be broken.
I also think that Get is preferable to ReadOnly.
Fixes #210 
```console
$ redis-cli -p 6379
127.0.0.1:6379> SMEMBERS OVAL#ubuntu#20#PKG#bird
1) "oval:com.ubuntu.focal:def:2019161590000000"
2) "oval:com.ubuntu.focal:def:2018120660000000"
127.0.0.1:6379> SADD OVAL#ubuntu#20#PKG#bird oval:com.ubuntu.focal:def:test
(integer) 1 …
```
> feat(redis): exit with error for possible DB corruption

- models/ubuntu/types.go
- models/ubuntu/ubuntu.go
- models/ubuntu/ubuntu_test.go
fixed a bug that packages were not included when fetching
```console
$ goval-dictionary fetch ubuntu 22.04
INFO[04-25|07:30:09] Fetching...                              URL=https://security-metadata.canonical.com/oval/oci.com.ubuntu.jammy.cve.oval.xml.bz2
INFO[04-25|07:30:13] Fetched                                  File=oci.com.ubuntu.jammy.cve.oval.xml.bz2 Count=11637 Timestamp=2023-04-24T21:10:16
WARN[04-25|07:30:13] Failed to parse string                   timeformat="[2006-01-02 2006-01-02 15:04:05 2006-01-02 15:04:05 +0000 2006-01-02 15:04:05 UTC]" target string="2023-02-14 10:00:00 PST"
WARN[04-25|07:30:13] Failed to parse string                   timeformat="[2006-01-02 2006-01-02 15:04:05 2006-01-02 15:04:05 +0000 2006-01-02 15:04:05 UTC]" target string="2023-02-14 10:00:00 PST" …
```
> fix(fetch/ubuntu): support oci oval

- commands/fetch-redhat.go
- fetcher/redhat/redhat.go
- fetcher/util/fetcher.go
- models/redhat/redhat.go
- models/redhat/redhat_test.go
OVALv1 data is no longer updated as of April 5, 2023, so OVALv2 is used.
```console
$ curl -s https://access.redhat.com/security/data/oval/com.redhat.rhsa-RHEL9.xml.bz2 | bunzip2 --stdout | grep "timestamp"
<oval:timestamp>2023-04-05T15:46:46</oval:timestamp>
```
However, there seems to be some vulnerability information that is in OVALv1 but not in OVALv2, so OVALv1 is used to supplement the information.
verified that we see the CVE in the new DB
```console
$ goval-dictictionary fetch redhat 5 6 7 8 9
INFO[05-09|09:46:58] Fetching...                              URL=https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2
INFO[05-09|09:46:58] Fetching...                              URL=https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL6.xml.bz2 …
```
> use redhat oval v2

- commands/fetch-redhat.go
- go.mod
- go.sum
- models/redhat/redhat.go
- models/redhat/redhat_test.go
Fixed to include both packages when they have the same package name but different ModularityLabel.
And when importing packages that have the same package name but different versions, we used to rely on the order in which they were written in OVAL, but now we use the new version.
Then, OVALv1 defines non-RHEL5 package information among RHEL5 ones. We have tried to exclude such packages that are not the target version.
```xml
<definition class="patch" id="oval:com.redhat.rhsa:def:20202774" version="638">
<metadata>
<title>RHSA-2020:2774: virt:rhel security update (Important)</title>
...
</metadata>
<criteria operator="OR">
<criterion comment="Red Hat Enterprise Linux must be installed" test_ref="oval:com.redhat.rhba:tst:20191992005"/>
<criteria operator="AND">
<criteria operator="OR"> …
```
> fix(models/redhat): fix collectRedHatPacks

- fetcher/ubuntu/ubuntu.go
remove 19.10 and 20.10 OVALs as they are no longer available.
```console
$ goval-dictionary fetch ubuntu 19.10 20.10
INFO[06-12|14:44:28] Fetching...                              URL=https://people.canonical.com/~ubuntu-security/oval/oci.com.ubuntu.eoan.cve.oval.xml.bz2
INFO[06-12|14:44:28] Fetching...                              URL=https://people.canonical.com/~ubuntu-security/oval/oci.com.ubuntu.groovy.cve.oval.xml.bz2
Failed to fetch files. err: Failed to fetch. err: [Failed to write to output stream: Expected HTTP Status 200, received: "404 Not Found" Failed to write to output stream: Expected HTTP Status 200, received: "404 Not Found"]
```
```console
$ goval-dictionary fetch ubuntu 19.10 20.10
WARN[06-12|14:43:53] Skip unsupported ubuntu version.         version=19.10 …
```
> feat(fetcher/ubuntu): remove 404 releases

- .github/workflows/fetch.yml
- config/config.go
- fetcher/debian/debian.go
add Debian 12
```console
$ goval-dictionary fetch debian 12
INFO[06-15|10:10:08] Fetching...                              URL=https://www.debian.org/security/oval/oval-definitions-bookworm.xml
INFO[06-15|10:10:12] Fetched                                  File=oval-definitions-bookworm.xml Count=25734 Timestamp=2023-06-14T19:40:18.188-04:00
INFO[06-15|10:10:12] Refreshing...                            Family=debian Version=12
INFO[06-15|10:10:12] Inserting new Definitions... 
25731 / 25731 [----------------------------------------------] 100.00% 22602 p/s
INFO[06-15|10:10:14] Finish                                   Updated=25731
```
> feat(fetcher/debian): add Debian 12 bookworm

- fetcher/debian/debian.go
> fix(fetcher/debian): use bzip2 data

- commands/fetch-redhat.go
- fetcher/redhat/redhat.go
Fixes #322 
```console
$ goval-dictionary fetch redhat 5 6 7 8 9
INFO[07-14|03:35:45] Fetching...                              URL=https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL6.xml.bz2
INFO[07-14|03:35:45] Fetching...                              URL=https://access.redhat.com/security/data/oval/v2/RHEL6/rhel-6.oval.xml.bz2
Failed to fetch files. err: Failed to fetch. err: [Failed to HTTP GET. url: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL6.xml.bz2, response: &{Status:404 Not Found StatusCode:404 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept-Ranges:[bytes] Cache-Control:[max-age=0, no-cache, no-store] Content-Length:[4175] Content-Type:[text/html] Date:[Thu, …
```
> fix(fetcher/redhat): fetch oval v1

- models/ubuntu/ubuntu.go
fixed warning with timezone
```xml
<definition class="vulnerability" id="oval:com.ubuntu.jammy:def:2023257250000000" version="1">
<metadata>
<title>CVE-2023-25725 on Ubuntu 22.04 LTS (jammy) - medium.</title>
<description>HAProxy before 2.7.3 may allow a bypass of access control because HTTP/1 headers are inadvertently
lost in some situations, aka "request smuggling." The HTTP header parsers in HAProxy may accept empty header
field names, which could be used to truncate the list of HTTP headers and thus make some headers disappear
after being parsed and processed for HTTP/1.0 and HTTP/1.1. For HTTP/2 and HTTP/3, the impact is limited
because the headers disappear before being parsed and processed, as if they had not been sent by the client.
The fixed versions are 2.7.3, 2.6.9, 2.5.12, …
```
> fix(fetch/ubuntu): fix timezone warning

- fetcher/fedora/fedora.go
Fixes #330 
```console
$ goval-dictionary fetch fedora 36
INFO[08-01|13:38:11] start fetch data from repomd.xml of non-modular package 
INFO[08-01|13:38:11] Fetching...                              URL=https://dl.fedoraproject.org/pub/fedora/linux/updates/36/Everything/x86_64/repodata/repomd.xml
Failed to fetch files. err: fetchEverythingFedora. err: Failed to fetch feed file, err: Failed to fetch. err: [Failed to write to output stream: Expected HTTP Status 200, received: "404 Not Found"]
```
```console
$ goval-dictionary fetch fedora 36
INFO[08-01|13:39:22] start fetch data from repomd.xml of non-modular package 
INFO[08-01|13:39:22] Fetching...                              URL=https://archives.fedoraproject.org/pub/archive/fedora/linux/updates/36/Everything/x86_64/repodata/repomd.xml …
```
> fix(fetcher/fedora): change archive version

- fetcher/amazon/amazon.go
Fixes #328 
```console
$ goval-dictionary fetch amazon 2023
INFO[08-01|16:30:52] Fetching...                              URL=https://cdn.amazonlinux.com/al2023/core/mirrors/latest/x86_64/mirror.list
INFO[08-01|16:30:53] Fetching...                              URL=https://cdn.amazonlinux.com/al2023/core/guids/9cf1057036ef7d615de550a658447fad88617805da0cfc9b854ba0fb8a668466/x86_64/repodata/repomd.xml
INFO[08-01|16:30:53] Fetching...                              URL=https://cdn.amazonlinux.com/al2023/core/guids/9cf1057036ef7d615de550a658447fad88617805da0cfc9b854ba0fb8a668466/x86_64/repodata/updateinfo.xml.gz
INFO[08-01|16:30:53] Refreshing...                            Family=amazon Version=2023
INFO[08-01|16:30:53] Inserting new Definitions... 
269 / 269 …
```
> feat(fetcher/amazon): support kernel livepatch advisory in AL2023

- fetcher/amazon/amazon.go
- fetcher/debian/debian.go
- fetcher/fedora/fedora.go
- fetcher/suse/suse.go
- fetcher/ubuntu/ubuntu.go
- fetcher/util/fetcher.go
- go.mod
- go.sum
I think htcat is not necessary to fetch compressed OVAL or non-large files.
Also, I set up a User-Agent that can be recognized as goval-dictionary.
Fixes #336 
> feat(fetcher): don't do concurrency fetch by htcat and set User-Agent

- .github/workflows/fetch.yml
- GNUmakefile
- README.md
- config/config.go
delete 19.10 and 20.10 from document because unsupported
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.
* https://blog.github.com/2015-01-21-how-to-write-the-perfect-pull-request/
> fix(ubuntu) delete 19.10 and 20.10 from document because unsupported

- .github/workflows/fetch.yml
- GNUmakefile
- README.md
- config/config.go
- fetcher/ubuntu/ubuntu.go
- integration/diff_server_mode.py
add 23.10 (mantic minotaur)
```console
$ goval-dictionary fetch ubuntu 23.10
INFO[10-20|15:01:37] Fetching...                              URL=https://security-metadata.canonical.com/oval/oci.com.ubuntu.mantic.cve.oval.xml.bz2
INFO[10-20|15:01:41] Fetched                                  File=oci.com.ubuntu.mantic.cve.oval.xml.bz2 Count=10430 Timestamp=2023-10-19T15:09:48
INFO[10-20|15:01:41] Refreshing...                            Family=ubuntu Version=23.10
INFO[10-20|15:01:41] Inserting new Definitions... 
10430 / 10430 [----------------------------------------------] 100.00% 40121 p/s
INFO[10-20|15:01:41] Finish                                   Updated=10430
$ goval-dictionary select --by-package ubuntu 23.10 curl
CVE-2023-28321
{3744 9538 curl 7.88.1-10ubuntu1  false } …
```
> feat(ubuntu): add 23.10 (mantic minotaur)

- .github/workflows/fetch.yml
- fetcher/fedora/fedora.go
- fetcher/fedora/types.go
- fetcher/fedora/types_test.go
In fedora 39 Modular, an error occurs because updateinfo is not provided. 
However, if there are no package updates, updateinfo may not be provided, so ignore errors when updateinfo is not provided, especially in the case of modular.
```console
$ goval-dictionary fetch fedora 39
INFO[02-21|00:37:14] start fetch data from repomd.xml of non-modular package 
INFO[02-21|00:37:14] Fetching...                              URL=https://dl.fedoraproject.org/pub/fedora/linux/updates/39/Everything/x86_64/repodata/repomd.xml
INFO[02-21|00:37:15] start fetch updateinfo in repomd.xml 
INFO[02-21|00:37:15] Fetching...                              URL=https://dl.fedoraproject.org/pub/fedora/linux/updates/39/Everything/x86_64/repodata/1127f254261a7d8e50363c58285ae5306032e66ce8b46f02868f810344d0392f-updatei …
```
> fix(fetcher/fedora): ignore errors with missing modular updateinfo

- commands/fetch-redhat.go
- fetcher/redhat/redhat.go
fetch extras, supplementary, els advisories.
```console
$ goval-dictionary fetch redhat 6
$ goval-dictionary.master select --by-cveid redhat 6 CVE-2023-46847
------------------
[]models.Definition{}
```
```console
$ goval-dictionary fetch redhat 6
$ goval-dictionary.pr select --by-cveid redhat 6 CVE-2023-46847
RHSA-2023:6882: squid34 security update (Critical)
[{10917 1839 CVE-2023-46847  8.6/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:H CWE-120 critical https://access.redhat.com/security/cve/CVE-2023-46847 20231019}]
RHSA-2023:6884: squid security update (Critical)
[{17170 2889 CVE-2023-46847  8.6/CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:H CWE-120 critical https://access.redhat.com/security/cve/CVE-2023-46847 20231019}]
------------------
[]models.Definition{
models.Definition{
ID: …
```
> feat(fetcher/redhat): fetch extras, supplementary, els advisories

- db/rdb.go
- models/suse/suse.go
In the CVE part of OVAL provided by SUSE, information indicating the source such as "at NVD" and "at SUSE" has been added to the part where the CVE ID is expected.
However, due to this, when you want to search by CVE ID, it does not match completely and cannot be found. Therefore, in this PR, the suffix is removed from the CVE ID part. Source can also be determined from Href.
Also, when searching by CVE ID or Package, the definitions will be duplicated, so we use the definition ID to make them unique.
```console
$ goval-dictionary fetch suse --suse-type suse-enterprise-server 15
$ goval-dictionary select --by-cveid suse.linux.enterprise.server 15.3 "CVE-2021-4024"
------------------
[]models.Definition{}
$ goval-dictionary select --by-cveid suse.linux.enterprise.server 15.3 "CVE-2021-4024 …
```
> fix(suse): remove CVE ID suffix

- .github/workflows/fetch.yml
- GNUmakefile
- README.md
- config/config.go
- fetcher/ubuntu/ubuntu.go
- integration/diff_server_mode.py
add ubuntu 24.04
```console
$ goval-dictionary fetch ubuntu 24.04
INFO[04-30|15:30:47] Fetching...                              URL=https://security-metadata.canonical.com/oval/oci.com.ubuntu.noble.cve.oval.xml.bz2
INFO[04-30|15:30:51] Fetched                                  File=oci.com.ubuntu.noble.cve.oval.xml.bz2 Count=12326 Timestamp=2024-04-30T03:09:44
INFO[04-30|15:30:51] Refreshing...                            Family=ubuntu Version=24.04
INFO[04-30|15:30:51] Inserting new Definitions... 
12326 / 12326 [---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 27661 p/s
INFO[04-30|15:30:52] Finish                                   Updated=12326
$ …
```
> feat(ubuntu): add 24.04 noble

- commands/fetch-redhat.go
- db/db.go
- db/db_test.go
- db/rdb.go
- fetcher/redhat/redhat.go
- models/models.go
- models/redhat/redhat.go
- models/redhat/redhat_test.go
- models/redhat/types.go
Red Hat OVALv2 provides OVALs that contains unpatched definitions. 
This PR supports those OVAL.
```console
$ goval-dictionary fetch redhat 8
$ goval-dictionary select --by-package redhat 8 "vim-common" | grep "oval:com.redhat.cve:def"
$
```
```console
$ goval-dictionary fetch redhat 8
$ goval-dictionary select --by-package redhat 8 "vim-common" | grep "oval:com.redhat.cve:def"
DefinitionID: "oval:com.redhat.cve:def:20222819",
...
$
```
> feat(fetch/redhat): fetch including-unpatched

- models/amazon/amazon.go
add another time layout for fetching amazon linux 2023
```console
$ goval-dictionary fetch amazon 2023
INFO[05-08|06:58:59] Fetching...                              URL=https://cdn.amazonlinux.com/al2023/core/mirrors/latest/x86_64/mirror.list
INFO[05-08|06:59:00] Fetching...                              URL=https://cdn.amazonlinux.com/al2023/core/guids/1418ab6fdc77352962b566b68d128e69ae0855c9a970f3355ca67ca576c60fee/x86_64/repodata/repomd.xml
INFO[05-08|06:59:00] Fetching...                              URL=https://cdn.amazonlinux.com/al2023/core/guids/1418ab6fdc77352962b566b68d128e69ae0855c9a970f3355ca67ca576c60fee/x86_64/repodata/updateinfo.xml.gz
INFO[05-08|06:59:00] Fetching...                              URL=https://cdn.amazonlinux.com/al2023/kernel-livepatch/mirrors/latest/x86_64/mi …
```
> fix(models/amazon): add time layout for 2023

- .github/workflows/fetch.yml
- GNUmakefile
- README.md
- fetcher/fedora/fedora.go
- integration/diff_server_mode.py
```console
$ goval-dictionary fetch fedora 37
INFO[06-13|14:38:55] start fetch data from repomd.xml of non-modular package 
INFO[06-13|14:38:55] Fetching...                              URL=https://dl.fedoraproject.org/pub/fedora/linux/updates/37/Everything/x86_64/repodata/repomd.xml
Failed to fetch files. err: fetchEverythingFedora. err: Failed to fetch feed file, err: Failed to fetch. err: [Failed to HTTP GET. url: https://dl.fedoraproject.org/pub/fedora/linux/updates/37/Everything/x86_64/repodata/repomd.xml, response: &{Status:404 Not Found StatusCode:404 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Content-Length:[196] Content-Security-Policy:[default-src 'none'; img-src 'self'] Content-Type:[text/html; charset=iso-8859-1] Date:[Thu, 13 Jun 2024 05:38:55 GMT] …
```
> fix(fetcher/fedora): fix archive version

- models/oracle/oracle.go
- models/oracle/oracle_test.go
Like Red Hat, Oracle also has vulnerabilities defined for modular packages, and it is necessary to collect modularity labels. This PR will collect modularity labels.
```console
$ curl -s https://linux.oracle.com/security/oval/com.oracle.elsa-all.xml.bz2 | bzip2 --decompress | xmllint --format - | grep -A50 "oval:com.oracle.elsa:def:20190975"
<definition id="oval:com.oracle.elsa:def:20190975" version="501" class="patch">
<metadata>
<title>
ELSA-2019-0975: container-tools:rhel8 security and bug fix update (IMPORTANT)
</title>
<affected family="unix">
<platform>Oracle Linux 8</platform>
</affected>
<reference source="elsa" ref_id="ELSA-2019-0975" ref_url="https://linux.oracle.com/errata/ELSA-2019-0975.html"/>
<reference source="CVE" ref_id="CVE-2019-5736" …
```
> fix(fetch/oracle): collect modularity label

- db/redis.go
Oracle, Amazon, and Fedora had Package Name and Arch for Key.
This allows you to find a really related Definition from the affected package and architecture.
```console
$ redis-cli -n 1 KEYS "OVAL#debian#12#PKG#bash"
1) "OVAL#debian#12#PKG#bash"
// It is not known which architectures will be affected!
$ redis-cli -n 1 SMEMBERS "OVAL#debian#12#PKG#bash"
1) "oval:org.debian:def:155603378603305228310656709111303140715" // Maybe Aarch64 is not affected!
2) "oval:org.debian:def:104452954611053805468881680603569149504"
3) "oval:org.debian:def:242327748915839239835482148445959073568"
...
$ redis-cli -n 1 KEYS "OVAL#oracle#8#PKG#bash#*"
1) "OVAL#oracle#8#PKG#bash#x86_64"
2) "OVAL#oracle#8#PKG#bash#aarch64"
// This …
```
> feat(db/redis): do not use Arch for Key in Oracle, Amazon, Fedora

- README.md
- commands/select.go
- db/db.go
- db/rdb.go
- db/redis.go
- models/debian/debian.go
- models/models.go
- server/server.go
select advisories and related cve ids
```console
$ goval-dictionary fetch redhat 9
$ goval-dictionary select advisories redhat 9
map[string][]string{
"RHSA-2022:7330": []string{
"CVE-2022-2585",
},
"RHSA-2023:4378": []string{
"CVE-2022-45869",
"CVE-2023-0458",
"CVE-2023-1998",
"CVE-2023-3090",
"CVE-2023-35788",
...
$ docker run --rm --name redis -d -p 127.0.0.1:6379:6379 redis
$ goval-dictionary fetch redhat 9 --dbtype redis --dbpath "redis://127.0.0.1:6379/1"
$ goval-dictionary select advisories redhat 9 --dbtype redis --dbpath "redis://127.0.0.1:6379/1"
map[string][]string{
"RHSA-2023:2653": []string{
"CVE-2023-2203",
},
"RHSA-2023:3423": []string{
"CVE-2023-24805",
},
"RHBA-2024:1127": []string{ …
```
> feat: select advisories

- fetcher/redhat/redhat.go
Fixes #409 
```console
$ pwd
/home/user/goval-dictionary
$ cat Dockerfile
FROM golang:alpine as builder
RUN apk add --no-cache \
git \
make
RUN git clone -b MaineK00n/poxy https://github.com/vulsio/goval-dictionary.git
RUN cd goval-dictionary && make install
FROM alpine:3.16
LABEL maintainer sadayuki-matsuno
ENV LOGDIR /var/log/goval-dictionary
ENV WORKDIR /goval-dictionary
RUN apk add --no-cache ca-certificates \
&& mkdir -p $WORKDIR $LOGDIR
COPY --from=builder /go/bin/goval-dictionary /usr/local/bin/
VOLUME ["$WORKDIR", "$LOGDIR"]
WORKDIR $WORKDIR
ENV PWD $WORKDIR
ENTRYPOINT ["goval-dictionary"]
CMD ["--help"]
$ cat docker-compose.yaml 
services:
app:
build: .
networks:       
- app_internal
proxy:
image: …
```
> fix(fetcher/redhat): fetch through proxy

- db/redis.go
With #402, Redis PKG keys no longer have Arch at the end, even if they are Amazon, Oracle, or Fedora.
https://github.com/vulsio/goval-dictionary/commit/1da5dfb8b28ada28b97359a407e86a9b58852fc1#diff-47497c0e5aee216ce040118072f4e2199cc00ec8f2c55059b2c4729ec026e101L324-L335
This part is for backward compatibility, and it is no longer necessary when most users are fetched with new goval-dictionary.
https://github.com/vulsio/goval-dictionary/blob/1da5dfb8b28ada28b97359a407e86a9b58852fc1/db/redis.go#L131-L207
For the hygiene of the code, I will erase it after a certain period of time.
> feat(db/redis): remove backward compatibility code

- .github/workflows/fetch.yml
- fetcher/fedora/fedora.go
- fetcher/util/fetcher.go
- go.mod
- go.sum
> fix(fetcher/fedora): determine mime type from the file extension
